version: "3"

services:
  db:
    image: mysql:5.7
    volumes:
      - ./db:/var/lib/mysql
    expose:
      - "3306"
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: second_hand_book
      MYSQL_USER: root
      MYSQL_PASSWORD: root
  
  php:
    depends_on:
      - db
    build: .
    volumes:
      - ./html:/var/www/html
    expose:
      - "80"
      - "443"
    restart: unless-stopped
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: root
    networks:
      - default
      - bridge

networks:
  bridge:
    driver: bridge
